services:
  server:
    image: ghcr.io/tresster/botge:main
    build:
      context: .
    environment:
      - NODE_ENV=production
      # discord
      - APP_ID=
      - DISCORD_TOKEN=
      
      # open ai
      #- OPENAI_API_KEY=
      
      # google
      #- CREDENTIALS=

      # twitch
      #- TWITCH_CLIENT_ID=
      #- TWITCH_SECRET=

      # MeiliSearch
      #- MEILISEARCH_API_KEY=
    volumes:
      - ./tmp:/app/tmp
      - ./data:/app/data
    restart: always
