services:
  server:
    image: ghcr.io/tresster/botge:main
    build:
      context: .
    environment:
      - NODE_ENV=production
      # discord
      - APP_ID=
      - DISCORD_TOKEN=
      
      # open ai
      - OPENAI_API_KEYTWO=
      
      # google
      - CREDENTIALS=

      # twitch
      - TWITCH_CLIENT_ID=
      - TWITCH_SECRET=
    volumes:
      - ./temp_gifs:/app/temp_gifs
    restart: always
