# @format

services:
  nginx:
    image: nginx:1.29.2-alpine
    mem_limit: 256m
    restart: always
    volumes:
      - ./nginx/cache:/var/www/cache:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  meilisearch:
    ports:
      - 7700:7700
    image: getmeili/meilisearch:v1.16
    mem_limit: 512m
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s
    volumes:
      - ./meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=SAMPLEMASTERKEY
      - MEILI_NO_ANALYTICS=true
      - MEILI_EXPERIMENTAL_REDUCE_INDEXING_MEMORY_USAGE
      - MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE

  botge:
    depends_on:
      - nginx
      - meilisearch
    image: ghcr.io/tresster/botge:main
    # Comment image and uncomment build, and context for local compose.
    # `docker compose up --build`
    # build:
    #   context: .
    mem_limit: 512m
    restart: always
    volumes:
      - ./tmp:/app/tmp
      - ./data:/app/data
    environment:
      - NODE_ENV=production

      # discord
      - APP_ID=
      - DISCORD_TOKEN=

      # open ai - optional
      #- OPENAI_API_KEY=

      # twitch - optional
      #- TWITCH_CLIENT_ID=
      #- TWITCH_SECRET=

      # MeiliSearch
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=SAMPLEMASTERKEY

      # nginx
      - LOCAL_CACHE_BASE=http://nginx:80

      # clips - optional
      - UPDATE_CLIPS_ON_STARTUP=true

      # embed server host, example: https://embedserver.com/t/ with / at the end - optional
      #- EMBED_SERVER_HOST=

      # Gemini - optional
      #- GEMINI_API_KEY=

      # Discord emojis. format: <:emoteName1:emoteId1>,<:emoteName2:emoteId2>
      #- DISCORD_EMOJIS=

      # join voice channel
      - JOIN_VOICE_CHANNEL=true
